# Generated by Django 4.1 on 2022-08-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_recipe', models.CharField(max_length=100)),
                ('favorite', models.BooleanField()),
                ('recipe_owner', models.CharField(max_length=80)),
                ('color_card', models.CharField(max_length=6)),
            ],
        ),
    ]
